# Generated by Django 5.2.1 on 2025-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование поставщика')),
                ('contact_person_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО контактного лица (общее)')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Основной телефон поставщика')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email поставщика')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Расчетный счет')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='УНП/ИНН')),
                ('bank_details', models.CharField(blank=True, max_length=255, verbose_name='Наименование и адрес банка')),
                ('supplier_manager_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО менеджера у поставщика')),
                ('supplier_manager_phone', models.CharField(blank=True, max_length=50, verbose_name='Конт. номер менеджера поставщика')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания/Комментарии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
                'permissions': [('can_edit_supplier_notes', 'Может редактировать примечания поставщика'), ('can_change_supplier_status', 'Может изменять статус активности поставщика')],
            },
        ),
    ]
