# Generated by Django 5.2.1 on 2025-06-01 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_cost_price'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата прихода')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа поставщика')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('expected', 'Ожидается'), ('received', 'Оприходовано'), ('partially_received', 'Частично оприходовано'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус поставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к поставке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Создал запись')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка (Приход товара)',
                'verbose_name_plural': 'Поставки (Приходы товара)',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Количество получено')),
                ('cost_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость за единицу (в этой поставке)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
                'unique_together': {('supply', 'product')},
            },
        ),
    ]
