# Generated by Django 5.2.1 on 2025-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supply_supplyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='quantity_remaining_in_batch',
            field=models.PositiveIntegerField(default=0, help_text='Сколько единиц из этой поставки еще осталось на складе', verbose_name='Остаток из этой партии'),
            preserve_default=False,
        ),
    ]
