# Generated by Django 5.2.1 on 2025-06-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplyitem_quantity_remaining_in_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='quantity_remaining_in_batch',
            field=models.PositiveIntegerField(default=0, help_text='Сколько единиц из этой поставки еще осталось на складе', verbose_name='Остаток из этой партии'),
        ),
    ]
