# Generated by Django 5.2.1 on 2025-06-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_correct_existing_supplyitem_batches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('can_edit_supplier_notes', 'Может редактировать примечания поставщика'), ('can_change_supplier_status', 'Может изменять статус активности поставщика'), ('can_edit_received_supply', 'Может редактировать оприходованные поставки')], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
