# Generated by Django 5.2.1 on 2025-06-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-receipt_date', '-created_at'], 'permissions': [('can_edit_received_supply', 'Может редактировать оприходованные поставки')], 'verbose_name': 'Поставка (Приход товара)', 'verbose_name_plural': 'Поставки (Приходы товара)'},
        ),
    ]
