# Generated by Django 5.2.1 on 2025-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('can_edit_supplier_notes', 'Может редактировать примечания поставщика'), ('can_change_supplier_status', 'Может изменять статус активности поставщика')], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AddField(
            model_name='supply',
            name='payment_transaction_created',
            field=models.BooleanField(default=False, help_text='Отмечается, когда для этой поставки была автоматически (через задачу) создана кассовая транзакция на оплату.', verbose_name='Расходная операция по оплате создана'),
        ),
    ]
