# Generated by Django 5.2.1 on 2025-06-09 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyitem',
            options={'ordering': ['product__name'], 'verbose_name': 'Позиция поставки', 'verbose_name_plural': 'Позиции поставки'},
        ),
        migrations.AddField(
            model_name='supply',
            name='expected_delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Ожидаемая дата поставки'),
        ),
        migrations.AddField(
            model_name='supply',
            name='received_at',
            field=models.DateTimeField(blank=True, editable=False, help_text="Заполняется автоматически при первом переходе поставки в статус 'Оприходовано'.", null=True, verbose_name='Дата и время оприходования'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа прихода'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('expected', 'Ожидается'), ('received', 'Оприходовано'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=20, verbose_name='Статус поставки'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='quantity_received',
            field=models.PositiveIntegerField(help_text='Фактическое количество товара, полученное в этой поставке.', verbose_name='Количество получено'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='quantity_remaining_in_batch',
            field=models.PositiveIntegerField(default=0, help_text='Сколько единиц из этой конкретной поставки еще осталось на складе. Управляется автоматически.', verbose_name='Остаток из этой партии на складе'),
        ),
    ]
