# Generated by Django 5.2.1 on 2025-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_supplyitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Сколько единиц из этой партии зарезервировано под заказы. Управляется автоматически.', verbose_name='В резерве (шт.)'),
        ),
    ]
