# Generated by Django 5.2.1 on 2025-06-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rocket SMS', max_length=100, verbose_name='Название настройки')),
                ('username', models.CharField(max_length=100, verbose_name='Логин Rocket SMS')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль Rocket SMS')),
                ('api_url', models.URLField(default='https://rocket-sms.by/api/', verbose_name='URL API')),
                ('sender_name', models.CharField(default='VeloTema', max_length=15, verbose_name='Имя отправителя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки SMS',
                'verbose_name_plural': 'Настройки SMS',
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рассылки')),
                ('recipient_type', models.CharField(choices=[('all_clients', 'Всем клиентам'), ('active_orders', 'Клиенты с активными заказами'), ('manual_list', 'Ручной список номеров')], default='manual_list', max_length=20, verbose_name='Кому отправить')),
                ('manual_phone_numbers', models.TextField(blank=True, help_text='Вводи номера через запятую. Пример: +375291234567, +375293334455', null=True, verbose_name='Номера телефонов')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Всего сообщений')),
                ('sent_messages', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('failed_messages', models.IntegerField(default=0, verbose_name='Не отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'SMS рассылка',
                'verbose_name_plural': 'SMS рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя получателя')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('rocket_sms_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в Rocket SMS')),
                ('api_response', models.TextField(blank=True, null=True, verbose_name='Ответ API')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms_service.smscampaign', verbose_name='Рассылка')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
            ],
            options={
                'verbose_name': 'SMS сообщение',
                'verbose_name_plural': 'SMS сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('message_text', models.TextField(help_text='Можно использовать переменные: {client_name}, {order_id}, {status}', max_length=800, verbose_name='Текст сообщения')),
                ('template_type', models.CharField(choices=[('order_ready', 'Заказ готов'), ('order_received', 'Заказ принят'), ('order_in_work', 'Заказ в работе'), ('promo', 'Рекламная рассылка'), ('reminder', 'Напоминание'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон SMS',
                'verbose_name_plural': 'Шаблоны SMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_service.smstemplate', verbose_name='Шаблон сообщения'),
        ),
    ]
