# Generated by Django 5.2.1 on 2025-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ['template_type', 'name'], 'verbose_name': 'Шаблон SMS', 'verbose_name_plural': 'Шаблоны SMS'},
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='template_code',
            field=models.CharField(default='default_template', help_text='Уникальный код для использования в коде (например: new_order_repair)', max_length=100, unique=True, verbose_name='Код шаблона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='api_url',
            field=models.URLField(default='http://api.rocketsms.by', help_text='URL для отправки запросов к API Rocket SMS', verbose_name='URL API'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='message_text',
            field=models.TextField(help_text='Можно использовать переменные: {client_name}, {order_number}, {order_type}, {total_amount}, {due_date}, {product_name}', verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='template_type',
            field=models.CharField(choices=[('new_order_repair', 'Новый заказ - Ремонт'), ('new_order_sale', 'Новый заказ - Продажа'), ('order_completed', 'Заказ выполнен'), ('order_ready', 'Заказ готов к выдаче'), ('meeting_reminder', 'Напоминание о встрече'), ('payment_reminder', 'Напоминание об оплате')], max_length=50, verbose_name='Тип шаблона'),
        ),
    ]
