# Generated by Django 5.2.1 on 2025-06-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например, 'Рабочий день исполнителя', 'Выходной день'", max_length=100, unique=True, verbose_name='Название правила цвета')),
                ('hex_color', models.CharField(help_text='Например, #RRGGBB или #RGB', max_length=7, verbose_name='HEX-код цвета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Правило цвета',
                'verbose_name_plural': 'Правила цветов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например, 'Цвет для рабочих смен исполнителей', 'Цвет для суббот'", max_length=255, verbose_name='Название условия назначения')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше значение (например, 100), тем выше приоритет правила. Правила с более высоким приоритетом перекрывают правила с более низким.', verbose_name='Приоритет')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Если указано, правило применяется только к этому дню недели.', null=True, verbose_name='День недели')),
                ('specific_date', models.DateField(blank=True, help_text='Если указано, правило применяется только к этой дате (например, для праздников).', null=True, verbose_name='Конкретная дата')),
                ('applies_to_workday', models.BooleanField(blank=True, help_text='Да - применяется к дню, когда у сотрудника есть смена. Нет - к дню, когда смены нет. Пусто - не учитывать этот критерий.', null=True, verbose_name='Применять к рабочему/выходному дню?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Правило активно?')),
                ('assigned_employee', models.ForeignKey(blank=True, help_text='Если указано, правило применяется только к этому сотруднику.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Конкретный сотрудник')),
                ('assigned_group', models.ForeignKey(blank=True, help_text="Если указано, правило применяется к сотрудникам из этой группы (игнорируется, если указан 'Конкретный сотрудник').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Группа сотрудников')),
                ('color_to_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafik.colorrule', verbose_name='Применяемый цвет')),
            ],
            options={
                'verbose_name': 'Правило назначения цвета',
                'verbose_name_plural': 'Правила назначения цветов',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['date', 'start_time'],
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
    ]
