# Generated by Django 5.2.1 on 2025-05-30 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0011_alter_order_payment_method_on_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calculated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая сумма начисления по заказу')),
                ('period_date', models.DateField(help_text='Дата, по которой это начисление попадет в зарплатный период (например, дата выдачи заказа).', verbose_name='Дата отнесения к периоду')),
                ('applied_base_rule_info', models.TextField(default='', help_text="Например: 'Ставка для Сотрудника X, тип заказа Y: 10% от услуг'", verbose_name='Основное примененное правило')),
                ('calculation_type', models.CharField(default='Сдельная оплата по заказу', max_length=100, verbose_name='Тип начисления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи расчета')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи расчета')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sm_salary_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sm_salary_calculation_for_employee', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Расчет зарплаты (Зарплаты)',
                'verbose_name_plural': 'Расчеты зарплаты (Зарплаты)',
                'ordering': ['-period_date', '-created_at', 'employee__username'],
                'unique_together': {('employee', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SalaryCalculationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.CharField(max_length=255, verbose_name='Описание источника (напр., название услуги)')),
                ('base_amount_for_calc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая сумма для расчета (сумма услуги/прибыль)')),
                ('applied_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Примененный процент (%)')),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма вознаграждения по этой позиции')),
                ('detail_type', models.CharField(default='service', max_length=20, verbose_name='Тип детализации (услуга/товар)')),
                ('order_service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderserviceitem', verbose_name='Позиция услуги в заказе')),
                ('salary_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='salary_management.salarycalculation', verbose_name='Основной расчет зарплаты')),
            ],
            options={
                'verbose_name': 'Детализация расчета (Зарплаты)',
                'verbose_name_plural': 'Детализации расчетов (Зарплаты)',
                'ordering': ['salary_calculation', 'source_description'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты')),
                ('payment_for_year', models.IntegerField(verbose_name='Год периода выплаты')),
                ('payment_for_month', models.IntegerField(verbose_name='Месяц периода выплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий к выплате')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sm_registered_salary_payments', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал выплату')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sm_salary_payments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты (Зарплаты)',
                'verbose_name_plural': 'Выплаты зарплаты (Зарплаты)',
                'ordering': ['-payment_date', 'employee__username'],
                'permissions': [('can_register_salary_payments', 'Может регистрировать выплаты зарплаты')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_percentage', models.DecimalField(decimal_places=2, help_text='Например, введите 10.00 для 10%', max_digits=5, verbose_name='Процент от суммы услуг (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ставка активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к ставке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_salary_rates', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_employee_rates', to='orders.ordertype', verbose_name='Тип заказа')),
            ],
            options={
                'verbose_name': 'Ставка сотрудника (Зарплаты)',
                'verbose_name_plural': 'Ставки сотрудников (Зарплаты)',
                'ordering': ['employee__username', 'order_type__name'],
                'permissions': [('can_manage_salary_rates', 'Может управлять зарплатными ставками')],
                'unique_together': {('employee', 'order_type')},
            },
        ),
    ]
