# Generated by Django 5.2.1 on 2025-05-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_delete_allemployeessalaryreportproxy_and_more'),
        ('salary_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEmployeesSalaryReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сводный отчет по зарплате',
                'verbose_name_plural': 'Сводный отчет по зарплате',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportaccesspermission',),
        ),
        migrations.AlterModelOptions(
            name='employeerate',
            options={'ordering': ['employee__username', 'order_type__name'], 'permissions': [('can_manage_salary_rates', 'Может управлять зарплатными ставками')], 'verbose_name': 'Ставка сотрудника (Зарплаты)', 'verbose_name_plural': 'Ставки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='salarycalculation',
            options={'ordering': ['-period_date', '-created_at', 'employee__username'], 'verbose_name': 'Расчет зарплаты (Зарплаты)', 'verbose_name_plural': 'Расчеты зарплаты'},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-payment_date', 'employee__username'], 'permissions': [('can_register_salary_payments', 'Может регистрировать выплаты зарплаты')], 'verbose_name': 'Выплата зарплаты (Зарплаты)', 'verbose_name_plural': 'Выплаты зарплаты'},
        ),
    ]
