# Generated by Django 5.2.1 on 2025-05-31 16:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproductitem_cost_price_at_sale'),
        ('salary_management', '0003_alter_allemployeessalaryreportproxy_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerate',
            options={'ordering': ['employee', 'order_type'], 'verbose_name': 'Ставка сотрудника', 'verbose_name_plural': 'Ставки сотрудников'},
        ),
        migrations.RemoveField(
            model_name='employeerate',
            name='notes',
        ),
        migrations.AddField(
            model_name='employeerate',
            name='product_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Процент от ПРИБЫЛИ ТОВАРОВ (%)'),
        ),
        migrations.AddField(
            model_name='employeerate',
            name='role_in_order',
            field=models.CharField(choices=[('manager', 'Менеджер в заказе'), ('performer', 'Исполнитель в заказе')], default='manager', max_length=15, verbose_name='Роль сотрудника в заказе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeerate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeerate',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype', verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='employeerate',
            name='service_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Процент от УСЛУГ (%)'),
        ),
    ]
