# Generated by Django 5.2.1 on 2025-05-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0004_alter_employeerate_options_remove_employeerate_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerate',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
