# Generated by Django 5.2.1 on 2025-05-31 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproductitem_cost_price_at_sale'),
        ('salary_management', '0005_employeerate_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerate',
            options={'ordering': ['employee', 'order_type', 'role_in_order'], 'verbose_name': 'Ставка сотрудника', 'verbose_name_plural': 'Ставки сотрудников'},
        ),
        migrations.AlterUniqueTogether(
            name='employeerate',
            unique_together={('employee', 'order_type', 'role_in_order')},
        ),
    ]
