# Generated by Django 5.2.1 on 2025-05-31 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproductitem_cost_price_at_sale'),
        ('salary_management', '0006_alter_employeerate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycalculationdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Детализация ЗП по услуге', 'verbose_name_plural': 'Детализации ЗП по услугам'},
        ),
        migrations.AddField(
            model_name='salarycalculationdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarycalculationdetail',
            name='applied_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Примененный процент'),
        ),
        migrations.AlterField(
            model_name='salarycalculationdetail',
            name='base_amount_for_calc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая сумма для расчета'),
        ),
        migrations.AlterField(
            model_name='salarycalculationdetail',
            name='detail_type',
            field=models.CharField(default='service', max_length=50, verbose_name='Тип детализации'),
        ),
        migrations.AlterField(
            model_name='salarycalculationdetail',
            name='earned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начислено'),
        ),
        migrations.AlterField(
            model_name='salarycalculationdetail',
            name='salary_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='salary_management.salarycalculation', verbose_name='Основной расчет зарплаты'),
        ),
        migrations.AlterField(
            model_name='salarycalculationdetail',
            name='source_description',
            field=models.CharField(max_length=255, verbose_name='Источник начисления (описание)'),
        ),
        migrations.CreateModel(
            name='ProductSalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Наименование товара (на момент расчета)')),
                ('product_price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи товара')),
                ('product_cost_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость товара на момент продажи')),
                ('profit_from_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибыль от товарной позиции')),
                ('applied_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Примененный % от прибыли')),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начислено с прибыли по товару')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('order_product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderproductitem', verbose_name='Товарная позиция заказа')),
                ('salary_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_profit_details', to='salary_management.salarycalculation', verbose_name='Основной расчет зарплаты')),
            ],
            options={
                'verbose_name': 'Детализация ЗП от прибыли по товару',
                'verbose_name_plural': 'Детализации ЗП от прибыли по товарам',
                'ordering': ['-created_at'],
            },
        ),
    ]
