# Generated by Django 5.2.1 on 2025-05-31 16:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproductitem_cost_price_at_sale'),
        ('salary_management', '0007_alter_salarycalculationdetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycalculation',
            options={'ordering': ['-period_date', '-created_at', 'employee__username'], 'verbose_name': 'Расчет зарплаты', 'verbose_name_plural': 'Расчеты зарплаты'},
        ),
        migrations.AlterUniqueTogether(
            name='salarycalculation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='role_context',
            field=models.CharField(choices=[('manager_earning', 'Начисление как Менеджеру'), ('performer_earning', 'Начисление как Исполнителю')], default='manager_earning', max_length=20, verbose_name='Контекст роли для начисления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='applied_base_rule_info',
            field=models.TextField(blank=True, default='', help_text="Например: 'Ставка для Сотрудника X, тип заказа Y, роль Менеджер: 10% от прибыли товаров'", verbose_name='Основное примененное правило'),
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='total_calculated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итоговая сумма начисления'),
        ),
        migrations.AlterUniqueTogether(
            name='salarycalculation',
            unique_together={('employee', 'order', 'role_context')},
        ),
    ]
