# Generated by Django 5.2.1 on 2025-06-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
    ]
