# Generated by Django 5.2.1 on 2025-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientgroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа клиентов', 'verbose_name_plural': 'Группы клиентов'},
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите номер в формате +375 (XX) XXX-XX-XX. Будет сохранен только в цифровом виде.', max_length=25, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
