# Generated by Django 5.2.1 on 2025-05-27 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_client_alter_order_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название кассы')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Текущий баланс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кассы')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название статьи расхода')),
            ],
            options={
                'verbose_name': 'Статья расхода',
                'verbose_name_plural': 'Статьи расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип транзакции')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=10, verbose_name='Метод платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание/Комментарий')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cash_register.cashregister', verbose_name='Касса')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='orders.order', verbose_name='Заказ (если применимо)')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='cash_register.expensecategory', verbose_name='Статья расхода (если расход)')),
            ],
            options={
                'verbose_name': 'Кассовая транзакция',
                'verbose_name_plural': 'Кассовые транзакции',
                'ordering': ['-timestamp'],
            },
        ),
    ]
