# Generated by Django 5.2.1 on 2025-05-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='is_default_for_card',
            field=models.BooleanField(default=False, verbose_name='Касса по умолчанию для карт'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='is_default_for_cash',
            field=models.BooleanField(default=False, verbose_name='Касса по умолчанию для наличных'),
        ),
    ]
