# Generated by Django 5.2.1 on 2025-05-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_cashregister_is_default_for_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOverviewReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Обзор кассы (Отчет)',
                'verbose_name_plural': 'Обзор кассы (Отчет)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cash_register.cashregister',),
        ),
    ]
