# Generated by Django 5.2.1 on 2025-05-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cash_register', '0003_cashoverviewreportproxy'),
        ('orders', '0009_alter_order_payment_method_on_closure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashOverviewReportProxy',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Если группы не выбраны, доступ к кассе может быть ограничен (например, только суперпользователям или по другой логике).', to='auth.group', verbose_name='Группы с доступом к этой кассе'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='till_type',
            field=models.CharField(choices=[('retail_point', 'Касса торговой точки'), ('main_organization', 'Главная касса организации')], default='retail_point', max_length=20, verbose_name='Тип кассы'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='paired_transfer_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_paired_transfer', to='cash_register.cashtransaction', verbose_name='Парная транзакция перемещения'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='is_default_for_card',
            field=models.BooleanField(default=False, verbose_name='Касса по умолчанию для карт (из заказов)'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='is_default_for_cash',
            field=models.BooleanField(default=False, verbose_name='Касса по умолчанию для наличных (из заказов)'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='orders.order', verbose_name='Заказ (если приход от заказа)'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Внутреннее перемещение')], max_length=10, verbose_name='Метод операции'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Приход (от заказа/внешний)'), ('expense', 'Расход (внешний)'), ('transfer_out', 'Перемещение (Расход)'), ('transfer_in', 'Перемещение (Приход)')], max_length=20, verbose_name='Тип транзакции'),
        ),
        migrations.CreateModel(
            name='CashOverviewReportProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Обзор кассы (Отчет)',
                'verbose_name_plural': 'Обзор кассы (Отчет)',
                'managed': False,
            },
        ),
    ]
