# Generated by Django 5.2.1 on 2025-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cash_register', '0004_delete_cashoverviewreportproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['name'], 'permissions': [('can_transfer_funds', 'Может перемещать средства между кассами')], 'verbose_name': 'Касса', 'verbose_name_plural': 'Кассы'},
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Если группы не выбраны, доступ к кассе может быть ограничен.', to='auth.group', verbose_name='Группы с доступом к этой кассе'),
        ),
    ]
