# Generated by Django 5.2.1 on 2025-06-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0005_alter_cashregister_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'ordering': ['-timestamp'], 'permissions': [('can_view_gko_cash_transactions', 'Может просматривать транзакции ГКО')], 'verbose_name': 'Кассовая транзакция', 'verbose_name_plural': 'Кассовые транзакции'},
        ),
    ]
