# Generated by Django 5.2.1 on 2025-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0006_alter_cashtransaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Статья расходов', 'verbose_name_plural': 'Статьи расходов'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_default_for_supply_payment',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта статья должна автоматически использоваться при оплате поставок.', verbose_name='Статья по умолчанию для оплаты поставок'),
        ),
    ]
