# Generated by Django 5.2.1 on 2025-06-03 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0007_alter_expensecategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Статья расхода', 'verbose_name_plural': 'Статьи расходов'},
        ),
        migrations.AddField(
            model_name='cashregister',
            name='is_gko_for_supply_payment',
            field=models.BooleanField(default=False, help_text='Отметьте, если это ГКО, из которой могут оплачиваться поставки.', verbose_name='ГКО для оплаты поставок'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
