# Generated by Django 5.2.1 on 2025-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0008_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='expense_type_category',
            field=models.CharField(choices=[('mandatory', 'Обязательные'), ('optional', 'Необязательные')], default='optional', max_length=20, verbose_name='Категория статьи расхода'),
        ),
    ]
