# Generated by Django 5.2.1 on 2025-06-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatuscolor',
            options={'ordering': ['status_key'], 'permissions': [('can_manage_status_colors', 'Может управлять цветами статусов заказов')], 'verbose_name': 'Цвет статуса заказа', 'verbose_name_plural': 'Цвета статусов заказов'},
        ),
    ]
