# Generated by Django 5.2.1 on 2025-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiconfig', '0002_alter_orderstatuscolor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyStatusColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(choices=[('draft', 'Черновик'), ('expected', 'Ожидается'), ('received', 'Оприходовано'), ('partially_received', 'Частично оприходовано'), ('cancelled', 'Отменено')], max_length=50, unique=True, verbose_name='Ключ статуса поставки')),
                ('status_name', models.CharField(blank=True, help_text="Например, 'Оприходовано', 'Ожидается'", max_length=100, verbose_name='Наименование статуса (для отображения)')),
                ('hex_color', models.CharField(default='#000000', help_text='Например, #FFFFFF для белого или #008000 для зеленого', max_length=7, verbose_name='Цвет HEX')),
            ],
            options={
                'verbose_name': 'Цвет статуса поставки',
                'verbose_name_plural': 'Цвета статусов поставок',
            },
        ),
    ]
