# Generated by Django 5.2.1 on 2025-06-06 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiconfig', '0004_taskstatuscolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDueDateColorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название правила (для админки)')),
                ('days_threshold', models.IntegerField(help_text="Количество дней относительно СЕГОДНЯШНЕЙ ДАТЫ. Положительное: осталось N дней до срока. 0: срок сегодня. Отрицательное: просрочено на N дней (например, -1 для 'просрочено на 1 день').", verbose_name='Порог (дней)')),
                ('operator', models.CharField(choices=[('lte', 'Осталось/Просрочено дней <= Порога'), ('gte', 'Осталось/Просрочено дней >= Порога'), ('eq', 'Осталось/Просрочено дней == Порогу')], default='lte', max_length=10, verbose_name="Оператор сравнения для 'дней до срока'")),
                ('hex_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Введите корректный HEX-код цвета (например, #RRGGBB)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='HEX-код цвета')),
                ('priority', models.PositiveIntegerField(default=10, help_text='Меньшее значение означает более высокий приоритет. Правила с одинаковым приоритетом применяются в порядке их ID.', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило цвета для срока заказа',
                'verbose_name_plural': 'Правила цветов для сроков заказов',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='orderstatuscolor',
            name='status_key',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('awaiting', 'Ожидается'), ('ready', 'Готов'), ('delivering', 'В доставке'), ('issued', 'Выдан'), ('cancelled', 'Отменен')], max_length=20, unique=True, verbose_name='Статус заказа (ключ)'),
        ),
    ]
