# Generated by Django 5.2.1 on 2025-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Права доступа к отчетам',
                'verbose_name_plural': 'Права доступа к отчетам',
                'permissions': [('view_stock_summary_report', 'Может просматривать сводный отчет по остаткам')],
            },
        ),
        migrations.CreateModel(
            name='StockSummaryReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сводный отчет по остаткам',
                'verbose_name_plural': 'Сводный отчет по остаткам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportaccesspermission',),
        ),
    ]
