# Generated by Django 5.2.1 on 2025-05-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportaccesspermission',
            options={'permissions': [('view_stock_summary_report', 'Может просматривать сводный отчет по остаткам'), ('view_cash_overview_report', 'Может просматривать отчет по кассе')], 'verbose_name': 'Права доступа к отчетам', 'verbose_name_plural': 'Права доступа к отчетам'},
        ),
    ]
