# Generated by Django 5.2.1 on 2025-05-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportaccesspermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Мой отчет по зарплате',
                'verbose_name_plural': 'Мои отчеты по зарплате',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportaccesspermission',),
        ),
        migrations.AlterModelOptions(
            name='reportaccesspermission',
            options={'permissions': [('view_stock_summary_report', 'Может просматривать сводный отчет по остаткам'), ('view_cash_overview_report', 'Может просматривать отчет по кассе'), ('view_all_employee_salaries', 'Может просматривать все зарплаты сотрудников')], 'verbose_name': 'Права доступа к отчетам', 'verbose_name_plural': 'Права доступа к отчетам'},
        ),
    ]
