# Generated by Django 5.2.1 on 2025-05-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_employeesalaryreportproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEmployeesSalaryReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сводный отчет по зарплате (все сотрудники)',
                'verbose_name_plural': 'Сводный отчет по зарплате (все сотрудники)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportaccesspermission',),
        ),
    ]
