# Generated by Django 5.2.1 on 2025-05-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_allemployeessalaryreportproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllEmployeesSalaryReportProxy',
        ),
        migrations.AlterModelOptions(
            name='employeesalaryreportproxy',
            options={'verbose_name': 'Мой отчет по зарплате', 'verbose_name_plural': 'Мой отчет по зарплате'},
        ),
    ]
