# Generated by Django 5.2.1 on 2025-06-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_delete_allemployeessalaryreportproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Отчет по расходам',
                'verbose_name_plural': 'Отчет по расходам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.reportaccesspermission',),
        ),
        migrations.AlterModelOptions(
            name='reportaccesspermission',
            options={'permissions': [('view_stock_summary_report', 'Может просматривать сводный отчет по остаткам'), ('view_cash_overview_report', 'Может просматривать отчет по кассе'), ('view_all_employee_salaries', 'Может просматривать все зарплаты сотрудников'), ('view_expense_report', 'Может просматривать отчет по расходам')], 'verbose_name': 'Права доступа к отчетам', 'verbose_name_plural': 'Права доступа к отчетам'},
        ),
    ]
