# Generated by Django 5.2.1 on 2025-06-03 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cash_register', '0006_alter_cashtransaction_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус (задача полностью закрыта)')),
                ('order_in_list', models.PositiveIntegerField(default=0, verbose_name='Порядок для сортировки')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['order_in_list', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название типа задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('default_visibility_groups', models.ManyToManyField(blank=True, help_text='Задачи этого типа будут автоматически видны пользователям из указанных групп', to='auth.group', verbose_name='Группы с автоматической видимостью')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического выполнения')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('assigned_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group_tasks', to='auth.group', verbose_name='Исполнитель (группа)')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель (пользователь)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип связанного объекта')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
                ('payment_cash_register_for_supply', models.ForeignKey(blank=True, help_text="Заполняется для задач типа 'Оформить оплату поставки' перед переводом в статус 'Готово к выполнению'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash_register.cashregister', verbose_name='Касса для оплаты поставки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.taskstatus', verbose_name='Статус задачи')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasktype', verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
