# Generated by Django 5.2.1 on 2025-06-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0008_alter_expensecategory_options_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_cash_register_for_supply',
            field=models.ForeignKey(blank=True, help_text="Заполняется для задач типа 'Оформить оплату поставки' перед переводом в статус 'Готово к выполнению'", limit_choices_to={'is_gko_for_supply_payment': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash_register.cashregister', verbose_name='Касса для оплаты поставки'),
        ),
    ]
