# Generated by Django 5.2.1 on 2025-05-30 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Импорт прайс-листа товаров',
                'verbose_name_plural': 'Импорт прайс-листа товаров',
                'permissions': [('can_import_product_prices', 'Может импортировать прайс-листы товаров')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название типа документа')),
                ('placeholders_hint', models.TextField(blank=True, help_text='Опишите здесь основные плейсхолдеры, доступные для этого типа документа. Например: #Номер_Заказа#, #Дата_Заказа#, #Клиент_Имя# и т.д. Для списков: #СписокТоваров_Начало# ... #Поз_Название# ... #СписокТоваров_Конец#', verbose_name='Подсказка по доступным плейсхолдерам')),
                ('related_model', models.ForeignKey(help_text="Выберите модель, данные из которой будут в основном использоваться в этом типе документа (например, 'Заказ').", on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Связанная модель (основной источник данных)')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('template_content', models.TextField(help_text='Используйте текст и плейсхолдеры вида #ИМЯ_ПЛЕЙСХОЛДЕРА#. Список доступных плейсхолдеров см. в описании выбранного Типа документа. Можно использовать базовые HTML теги для форматирования (например, < b >, < i >, < p >, < br >, таблицы).', verbose_name='Содержимое шаблона (HTML с плейсхолдерами)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (доступен для генерации)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('allowed_editing_groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Группы с правом редактирования этого шаблона')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='utils.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['document_type', 'name'],
                'unique_together': {('document_type', 'name')},
            },
        ),
    ]
