# Generated by Django 5.2.1 on 2025-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportStockLevelsTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Инструмент: Выгрузка остатков',
                'verbose_name_plural': 'Инструменты: Выгрузка остатков',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportSupplyItemsTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Инструмент: Импорт позиций Поставки (CSV)',
                'verbose_name_plural': 'Инструменты: Импорт позиций Поставки (CSV)',
                'managed': False,
            },
        ),
    ]
