# Generated by Django 5.2.1 on 2025-06-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_exportstocklevelstool_importsupplyitemstool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок заметки')),
                ('content', models.TextField(help_text='Подробное описание функции или инструкция', verbose_name='Содержание заметки')),
                ('category', models.CharField(choices=[('export', 'Экспорт данных'), ('import', 'Импорт данных'), ('api', 'API и интеграции'), ('reports', 'Отчёты'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Категория')),
                ('is_important', models.BooleanField(default=False, help_text='Отметить как важную (будет выделена)', verbose_name='Важная заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Служебная заметка',
                'verbose_name_plural': 'Служебные заметки',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
    ]
