# Generated by Django 5.2.1 on 2025-06-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_servicenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicenote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Служебная заметка', 'verbose_name_plural': 'Служебные заметки'},
        ),
        migrations.AddField(
            model_name='servicenote',
            name='is_admin_only',
            field=models.BooleanField(default=False, help_text="Эту заметку смогут видеть только пользователи из группы 'Администраторы'", verbose_name='Только для администрации'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который создал заметку', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
    ]
