# Generated by Django 5.2.1 on 2025-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара на момент заказа'),
        ),
        migrations.AlterField(
            model_name='orderserviceitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена услуги на момент заказа'),
        ),
    ]
