# Generated by Django 5.2.1 on 2025-05-27 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0003_alter_orderproductitem_price_at_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
            preserve_default=False,
        ),
    ]
