# Generated by Django 5.2.1 on 2025-05-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_client_alter_order_employee'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderserviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_service_items', to='orders.service', verbose_name='Услуга'),
        ),
    ]
