# Generated by Django 5.2.1 on 2025-05-27 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
        ('orders', '0005_alter_orderproductitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method_on_closure',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=10, null=True, verbose_name='Метод оплаты при закрытии'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash_register.cashregister', verbose_name='Касса для зачисления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('awaiting_payment', 'Ожидает оплаты'), ('paid_cash', 'Оплачен наличными'), ('paid_card', 'Оплачен картой'), ('assembled', 'Собран'), ('shipped', 'Отгружен'), ('completed', 'Завершен (оплачен и отгружен)'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
