# Generated by Django 5.2.1 on 2025-05-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_cashregister_is_default_for_card_and_more'),
        ('orders', '0006_order_payment_method_on_closure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash_register.cashregister', verbose_name='Касса для зачисления (авто)'),
        ),
    ]
