# Generated by Django 5.2.1 on 2025-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_service_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method_on_closure',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Внутреннее перемещение')], max_length=10, null=True, verbose_name='Метод оплаты при закрытии'),
        ),
    ]
