# Generated by Django 5.2.1 on 2025-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordertype_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method_on_closure',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=20, null=True, verbose_name='Метод оплаты при закрытии'),
        ),
    ]
