# Generated by Django 5.2.1 on 2025-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_performer_alter_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductitem',
            name='cost_price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость на момент заказа'),
        ),
    ]
