# Generated by Django 5.2.1 on 2025-05-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproductitem_cost_price_at_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_order_type_dynamically', 'Может изменять тип заказа (динамически)')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
