# Generated by Django 5.2.1 on 2025-06-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_repaired_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_order_type_dynamically', 'Может изменять тип заказа (динамически)'), ('can_view_target_cash_register', 'Может видеть кассу для зачисления в заказе')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
