# Generated by Django 5.2.1 on 2025-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_repaired_item_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('awaiting', 'Ожидается'), ('ready', 'Готов'), ('delivering', 'В доставке'), ('issued', 'Выдан'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
