# Generated by Django 5.2.1 on 2025-06-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, help_text='Плановая дата, до которой заказ должен быть выполнен.', null=True, verbose_name='Срок выполнения до'),
        ),
    ]
